# Cute startup message for "Ignatz" cluster
echo ""
echo ""
echo "Welcome to the Ignatz GPU cluster!"
echo "    You are in the MASTER node"
echo ""
echo "    _______ ---------------"
echo "   /______/| ---- ZIP! ----"
echo "   |______|/ --------------"
echo ""
echo ""
echo "Set up by Quinn Stratton and Dr. Ray Klump"
echo "Lewis University Computer and Mathematical Sciences"
echo ""
