echo ""
echo "Welcome to the Krazy Kluster!"
echo "You are in the MASTER node of a four node Raspberry Pi cluster"
echo ""
echo " ________"
echo "/_______/|"
echo "|_______|/"
echo " |   |   |"
echo " |  POW! |"
echo " |   |   |"
echo ""
echo "Set up by Quinn Stratton and Dr. Ray Klump"
echo "Lewis University Computer and Mathematical Sciences"
